{
    try{
        console.log(a)
    }catch(error){
        console.log(error)
    }
    let a = 1

    console.log(a)
}